[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"
# Use the below only if we're pulling in libmagick
#rustflags = [
#	"-C", "link-args=-Wl,-rpath-link,/home/dwagner/Documents/sysroots/beaglebone/lib/arm-linux-gnueabihf",
#	"-C", "link-args=-Wl,-rpath-link,/home/dwagner/Documents/sysroots/beaglebone/usr/lib/arm-linux-gnueabihf"]

[build]
target = "armv7-unknown-linux-gnueabihf"
