/* Generated by Yosys 0.23+25 (git sha1 b9b5899cc, gcc 9.4.0-1ubuntu1~20.04.1 -fPIC -Os) */

module EventXing(IClk, iEvent, OClk, iReady, oEvent);
  wire _00_;
  wire _01_;
  wire _02_;
  reg _03_ = 1'h0;
  reg _04_ = 1'h0;
  reg _05_ = 1'h0;
  reg _06_ = 1'h0;
  reg _07_ = 1'h0;
  reg _08_ = 1'h0;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  reg _15_ = 1'h1;
  wire _16_;
  input IClk;
  wire IClk;
  input OClk;
  wire OClk;
  input iEvent;
  wire iEvent;
  output iReady;
  wire iReady;
  wire ifartoggle;
  wire ifartogglemeta;
  wire ilcltoggle;
  wire ireadylcl;
  output oEvent;
  wire oEvent;
  wire ofartoggle;
  wire ofartogglemeta;
  wire ofartoggleq;
  wire olcltoggle;
  assign _00_ = ~ ireadylcl;
  assign _09_ = iEvent & _00_;
  assign _10_ = ~ _09_;
  assign _11_ = ~ 1'h1;
  assign _12_ = _11_ | _10_;
  always @* if (1'h1) assert(_15_);
  assign _13_ = ireadylcl & iEvent;
  assign _14_ = ~ ilcltoggle;
  always @(posedge IClk)
    _15_ <= _12_;
  assign _16_ = ofartoggle != ofartoggleq;
  assign _01_ = ifartoggle == ilcltoggle;
  assign _02_ = _13_ ? _14_ : ilcltoggle;
  always @(posedge IClk)
    _03_ <= _02_;
  always @(posedge IClk)
    _04_ <= olcltoggle;
  always @(posedge IClk)
    _05_ <= ifartogglemeta;
  always @(posedge OClk)
    _06_ <= ilcltoggle;
  always @(posedge OClk)
    _07_ <= ofartogglemeta;
  always @(posedge OClk)
    _08_ <= ofartoggle;
  assign ireadylcl = _01_;
  assign ilcltoggle = _03_;
  assign ifartogglemeta = _04_;
  assign ifartoggle = _05_;
  assign olcltoggle = ofartoggle;
  assign ofartogglemeta = _06_;
  assign ofartoggle = _07_;
  assign ofartoggleq = _08_;
  assign iReady = ireadylcl;
  assign oEvent = _16_;
endmodule
