[package]
name = "cloud_ceiling"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magick_rust = "0.17.0"
memmap = "0.7.0"
nix = { version = "0.26.2", features = ["ioctl"], default-features = false }
volatile = "<0.3.0"
